name: china_deals
description: Application mobile CHINA DEALS
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.1.1
  firebase_auth: ^4.2.3
  cloud_firestore: ^4.0.3
  provider: ^6.0.5

flutter:
  uses-material-design: true